services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - mongodb
    volumes:
      - ./raw:/app/data/raw
      - ./processed:/app/data/processed
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./logs:/app/logs

  db:
    image: postgres:15
    container_name: fastapi-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7.0
    container_name: fastapi-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: movies_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./data:/docker-entrypoint-initdb.d/data:ro
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  postgres_data:
  mongo_data: